//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public string Id { get; set; }
        public string Pin { get; set; }
        public string ConstraintDescript { get; set; }
        public string Domicile_Name { get; set; }
        public string Graduation_Name { get; set; }
        public string PersonalConstraint_Code { get; set; }
        public Nullable<int> Preference_Code { get; set; }
        public string Alias { get; set; }
    }
}
